language: php

php:
  - 5.3

mysql:
  database: drupal
  username: root
  encoding: utf8

before_script:
  - sudo apt-get install apache2
  - sudo a2enmod actions
  - sudo a2enmod rewrite
  - sudo service apache2 restart    
  - "mysql -e 'create database drupal;'"
  - pear channel-discover pear.drush.org
  - pear install drush/drush
  - phpenv rehash
  - bash scripts/ci/setup
  - bash scripts/build
  - cd www
  - drush si garmentbox --db-url=mysql://root:@127.0.0.1/drupal --account-pass=admin --yes

  # Create a behat configuration file.
  - cd profiles/garmentbox/behat
  - cp behat.local.yml.travis behat.local.yml
  - composer install

script:
  - ./bin/behat

