language: php

php:
  - 5.3

mysql:
  database: drupal
  username: root
  encoding: utf8

before_script:
  - "mysql -e 'create database drupal;'"
  - pear channel-discover pear.drush.org
  - pear install drush/drush
  - phpenv rehash
  - bash scripts/ci/setup
  - bash scripts/build
  # Prepare the dummy test.
  - chmod +x ./scripts/ci/test.sh
  - cd www
  - drush si opengizra --db-url=mysql://root:@127.0.0.1/drupal --account-pass=admin --yes
  - drush cc all --yes
  - touch ../opengizra/behat/behat.local.yml
  - cd ..

# Dummy script to return "exit 0", until Behat is in place.
script: ./scripts/ci/test.sh
