language: php

php:
  - 5.4

mysql:
  database: drupal
  username: root
  encoding: utf8

before_script:
  - "mysql -e 'create database drupal;'"
  - pear channel-discover pear.drush.org
  - pear install drush/drush
  - phpenv rehash
  - bash scripts/ci/setup
  - bash scripts/build
  - cd www
  - drush si garmentbox --db-url=mysql://root:@127.0.0.1/drupal --account-pass=admin --yes
  - drush cc all --yes
  - cd ..

  # Create a behat configuration file.
  - cd garmentbox/behat
  - cp behat.local.yml.travis behat.local.yml

  # Create Drush alias.
  - cp aliases.drushrc.php ~/.drush/
  - composer install

  # Patch drupalextension.
  - cd garmentbox/behat/vendor/drupal/drupal-extension/
  - wget http://drupal.org/files/drupalextension_store_uid_from_drush.diff
  - git apply drupalextension_store_uid_from_drush.diff
  - cd ../../../../../

script:
  # Create display.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start

  - sudo drush @garmentbox runserver --server=builtin 80 &

  # Run selenium.
  - wget http://selenium.googlecode.com/files/selenium-server-standalone-2.25.0.jar
  - java -jar selenium-server-standalone-2.25.0.jar -p 4444 &
  - sleep 5

  - ./bin/behat --tags=~@wip

