language: php

php:
  - 5.3

mysql:
  database: drupal
  username: root
  encoding: utf8

before_script:
  - sudo apt-get install apache2
  - sudo a2enmod actions
  - sudo a2enmod rewrite
  - "mysql -e 'create database drupal;'"
  - pear channel-discover pear.drush.org
  - pear install drush/drush
  - phpenv rehash
  - bash scripts/ci/setup
  - bash scripts/build
  - cd www
  - drush si opengizra --db-url=mysql://root:@127.0.0.1/drupal --account-pass=admin --yes
  - drush cc all --yes
  - cd ..

  # Create a behat configuration file.
  - cd opengizra/behat
  - cp behat.local.yml.travis behat.local.yml
  - cp aliases.drushrc.php ~/.drush/
  - composer install

+script:
  - ./bin/behat
