<?php

/**
 * Implements hook_migrate_api().
 */
function gb_migrate_migrate_api() {
  $mirgations = array(
    // Nodes.
    'GbCompaniesMigrate',
    'GbItemsMigrate',
    'GbItemVariantsMigrate',
    'GbMaterialsMigrate',
    'GbSeasonsMigrate',

    // Terms.
    'GbItemStatusTermsMigrate',
    'GbMaterialTypeTermsMigrate',
    'GbMeasurementUnitTermsMigrate',
    'GbSeasonStatusTermsMigrate',

    // Users.
    'GbUsersMigrate',
  );

  $api['api'] = 2;
  foreach ($mirgations as $mirgation) {
    $api['migrations'][$mirgation] = array('class_name' => 'GbUsersMigrate');
  }

  return $api;
}
