<?php
/**
 * @file
 * Code for the Garmentbox season feature.
 */

include_once 'garmentbox_season.features.inc';

/**
 * Implements hook_init().
 */
function garmentbox_season_init() {
  global $user;
  if (empty($user->uid)) {
    return;
  }

  if (drupal_is_front_page()) {
    _garmentbox_season_redirect_to_season();
  }
}

/**
 * Implements hook_menu().
 */
function garmentbox_season_menu() {
  $items['season/%/orders'] = array(
    'title' => 'Orders',
    'page callback' => 'garmentbox_order_get_orders_table',
    'page arguments' => array(1),
    'type' => MENU_CALLBACK,
    'access callback' => 'node_access',
    'access arguments' => array('view', 1),
  );

  $items['season/%/inventory'] = array(
    'title' => 'Inventory summary',
    'page callback' => 'garmentbox_inventory_get_summary',
    'page arguments' => array(1),
    'type' => MENU_CALLBACK,
    'access callback' => 'node_access',
    'access arguments' => array('view', 1),
  );

  return $items;
}

/**
 * Redirect from the front page to a season page.
 */
function _garmentbox_season_redirect_to_season() {
  // Find the last changed season.
  $query = new EntityFieldQuery();
  $result = $query->entityCondition('entity_type', 'node')
    ->propertyCondition('type', 'season')
    ->propertyCondition('status', NODE_PUBLISHED)
    ->propertyOrderBy('changed', 'DESC')
    ->range(0, 1)
    ->execute();

  if (empty($result)) {
    return;
  }

  $nid = key($result['node']);

  // Redirect from a season page to the season's items tab if there are no
  // items, otherwise redirecr to the tasks tab.
  if (!_garmentbox_season_count_view_rows('item_variants', $nid)) {
    drupal_goto("season/$nid/items");
  }
  else {
    drupal_goto("season/$nid");
  }
}

/**
 * Count the amount of rows on a season related view.
 *
 * @param $view_name
 *   The view name.
 * @param $nid
 *   Season NID.
 *
 * @return
 *   The amount of rows on the view.
 */
function _garmentbox_season_count_view_rows($view_name, $nid) {
  $view = views_get_view($view_name);
  $view->preview('panel_pane_1', array($nid));
  return $view->total_rows;
}

/**
 * Build the tabs list for a season node.
 *
 * @param $nid
 *   Season node ID.
 *
 * @return
 *   Themed item list of tabs.
 */
function garmentbox_season_get_tabs($nid) {
  $items = array();
  $items[] = l(t('Task List'), "node/$nid");
  $items[] = l(t('Items'), "season/$nid/items");
  $items[] = l(t('Inventory'), "season/$nid/inventory");
  $items[] = l(t('Orders'), "season/$nid/orders");
  $items[] = l(t('Production Orders'), "season/$nid/production-orders");

  return theme('item_list', array('items' => $items));
}
