<?php
/**
 * @file
 * Code for the Garmentbox Company feature.
 */

/**
 * Implements hook_ctools_plugin_directory().
 */
function gb_restful_ctools_plugin_directory($module, $plugin) {
  if ($module == 'restful') {
    return 'plugins/' . $plugin;
  }
}

/**
 *  Return image URLs based on image styles of multiple images.
 *
 * @param array $values
 *   Array with file arrays.
 *
 * @return array
 *   Array of arrays keyed by the image style and the url as the value.
 *
 * @see gb_restful_get_image_styles()
 */
function gb_restful_get_images_styles(array $values) {
  $return = array();
  foreach ($values as $file_array) {
    $return[] = gb_restful_get_image_styles($file_array);
  }

  return $return;
}


/**
 * Return image URLs based on image styles.
 *
 * @param array $file_array
 *   The image array.
 *
 * @return array
 *   Array keyed by the image style and the url as the value.
 */
function gb_restful_get_image_styles(array $file_array) {
  $uri = $file_array['uri'];
  $return = array(
    'original' => file_create_url($uri),
  );

  $image_styles = array(
    'thumbnail',
    'medium',
    'large',
  );

  foreach ($image_styles as $image_style) {
    $return[$image_style] = image_style_url($image_style, $uri);
  }
  return $return;
}
