<?php
/**
 * @file
 * Code for the Opengizra season feature.
 */

include_once 'opengizra_season.features.inc';

/**
 * Implements hook_ctools_plugin_directory().
 */
function opengizra_season_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implements hook_init().
 *
 * Redirect from the front page to a season page.
 */
function opengizra_season_init() {
  global $user;
  if (empty($user->uid)) {
    return;
  }

  if (!drupal_is_front_page()) {
    return;
  }

  // Find the last changed season.
  $query = new EntityFieldQuery();
  $result = $query->entityCondition('entity_type', 'node')
    ->propertyCondition('type', 'season')
    ->propertyCondition('status', NODE_PUBLISHED)
    ->propertyOrderBy('changed', 'DESC')
    ->range(0, 1)
    ->execute();

  if (empty($result)) {
    return;
  }

  $nid = key($result['node']);
  drupal_goto("node/$nid");
}
