<?php
/**
 * @file
 * Code for the Opengizra season feature.
 */

include_once 'opengizra_season.features.inc';

/**
 * Implements hook_ctools_plugin_directory().
 */
function opengizra_season_ctools_plugin_directory($module, $plugin) {
  if ($module == 'ctools') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implements hook_init().
 */
function opengizra_season_init() {
  global $user;
  if (empty($user->uid)) {
    return;
  }

  _opengizra_season_redirect_to_season();

  _opengizra_season_redirect_to_season_items();
}

/**
 * Redirect from the front page to a season page.
 */
function _opengizra_season_redirect_to_season() {
  if (!drupal_is_front_page()) {
    return;
  }

  // Find the last changed season.
  $query = new EntityFieldQuery();
  $result = $query->entityCondition('entity_type', 'node')
    ->propertyCondition('type', 'season')
    ->propertyCondition('status', NODE_PUBLISHED)
    ->propertyOrderBy('changed', 'DESC')
    ->range(0, 1)
    ->execute();

  if (empty($result)) {
    return;
  }

  $nid = key($result['node']);
  drupal_goto("season/$nid");
}

/**
 * Redirect from a season page to the season's items tab if there are no items.
 */
function _opengizra_season_redirect_to_season_items() {
  $node = menu_get_object();
  if (!$node || $node->type != 'season') {
    return;
  }

  // Query for an item of the season.
  $query = new EntityFieldQuery();
  $count = $query->entityCondition('entity_type', 'node')
    ->propertyCondition('type', 'item')
    ->propertyCondition('status', NODE_PUBLISHED)
    ->fieldCondition('field_season', 'target_id', $node->nid)
    ->range(0, 1)
    ->count()
    ->execute();

  // If there are no items at all, redirect to items page.
  if (!$count) {
    drupal_goto("season/{$node->nid}/items");
  }
}
